import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Werdykty — dopasowane do palety semantycznej GRUNT.
        zielony: { DEFAULT: "#1C8A5A", bg: "#E4F3EB", text: "#166534" },
        zolty: { DEFAULT: "#B5790B", bg: "#FBF0DA", text: "#8A5C08" },
        czerwony: { DEFAULT: "#C0392B", bg: "#FBE7E4", text: "#991b1b" },
        // Paleta GRUNT (design tokens, sekcja 10 wytycznych).
        grunt: {
          ink: "#16263F",
          ink2: "#23395c",
          ink3: "#1d3354",
          mint: "#6FE3C4",
          bg: "#E9EDF2",
          "bg-report": "#E1E6EC",
          surface: "#FFFFFF",
          "surface-2": "#FAFBFC",
          "surface-3": "#F4F6F9",
          "map-bg": "#EFF2F6",
          "border-input": "#C7D0DC",
          border: "#DDE3EB",
          "border-2": "#E2E6EC",
          divider: "#EEF1F5",
          "divider-row": "#F2F4F7",
          "border-soft": "#B9C4D2",
          text: "#16263F",
          "text-2": "#2A3F5F",
          "text-3": "#3A4D6B",
          "text-muted": "#5C6B82",
          "text-muted2": "#6B7A92",
          "text-faint": "#8E9BAE",
          "text-faint2": "#9AA7BA",
          "text-ghost": "#A9B5C6",
          young: "#0E7C8B",
          "young-bg": "#E0F0F2",
          senior: "#7A4A86",
          "senior-bg": "#F0E8F2",
          green: "#1C8A5A",
          "green-bg": "#E4F3EB",
          amber: "#B5790B",
          "amber-bg": "#FBF0DA",
          "amber-text": "#8A5C08",
          "amber-text2": "#9A6608",
          red: "#C0392B",
          "red-bg": "#FBE7E4",
          neutral: "#6B7A92",
          "neutral-bg": "#EDF0F4",
          "chart-1": "#2A6FA8",
          "chart-2": "#16263F",
          "chart-3": "#4A6491",
          "chart-4": "#6E8BB0",
          "chart-5": "#9DB1CE",
          "chart-6": "#B3C2D6",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "IBM Plex Sans", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "IBM Plex Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        card: "14px",
        panel: "12px",
        md: "10px",
        input: "9px",
        sm: "8px",
        xs: "6px",
        tag: "5px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(20,38,63,.04)",
        raised: "0 6px 22px rgba(20,38,63,.10)",
        elevated: "0 8px 24px rgba(20,38,63,.12)",
        sheet: "0 8px 40px rgba(20,38,63,.12)",
        modal: "0 24px 60px rgba(8,18,34,.4)",
      },
    },
  },
  plugins: [],
};

export default config;
